apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend-chart.fullname" . }}
  annotations: 
    {{- tpl (toYaml .Values.metrics.service.annotations) . | nindent 4 }}
  labels:
    {{- include "frontend-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.metrics.service.port }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "frontend-chart.selectorLabels" . | nindent 4 }}
