apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend-chart.fullname" . }}
  labels:
    {{- include "frontend-chart.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.metrics.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/path: "{{ .Values.metrics.path }}"
    prometheus.io/port: "{{ .Values.metrics.port }}"
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "frontend-chart.selectorLabels" . | nindent 4 }}
